#!/bin/bash
#
# Sets the temperature factors in the input PDB files to a specific value
#
# The value is specified with the manditory option "-o value".
#
# Accepts one or more PDB-format coordinate files on the command line
# If no files are specified, or "-" is used as a file name, the input is read
# from the standard input.
#
while getopts o: FLAG
do
  case "$FLAG" in
    o) OCC_VALUE="$OPTARG";;
    [?]) OPT_ERROR="YES";;
  esac
done
if [ -n "$OPT_ERROR" ] || [ -z "$OCC_VALUE" ]; then
 printf "Usage: %s -o value [file ...]\n" `basename $0` 1>&2
 exit 1
fi
shift $((OPTIND-1))
awk '{ if ( $0 ~ /^ATOM  |^HETATM/ ) { printf "%s%6.2f%s\n", substr($0,1,54), '${OCC_VALUE}', substr( $0, 61 ); } else print; }' $*
